# Generated by Django 5.0.6 on 2024-07-11 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0002_fornecedor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fornecedor",
            old_name="endereço",
            new_name="endereco",
        ),
        migrations.RenameField(
            model_name="produto",
            old_name="preço",
            new_name="preco",
        ),
    ]
