# Generated by Django 5.0.6 on 2024-07-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loja", "0003_rename_endereço_fornecedor_endereco_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="quantidade",
            field=models.IntegerField(default=0),
        ),
    ]
